on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Run Tests"]
    branches: [main]
    types: 
      - completed

name: Bump Version
jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout
        uses: actions/checkout@v3.3.0

      - name: 🚧 Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node }}

      - name: 🤖 Setup Project
        run: 'yarn'

      - name: 🆙 Bump Version
        run: |
          VERSION=$(cat manifest.json | awk 'match($0, "\"version\": \"([^\"]+)\"", m) {print m[1]}')
          BUMPED=$(echo $VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{if(length($NF+1)>length($NF))$(NF-1)++; $NF=sprintf("%0*d", length($NF), ($NF+1)%(10^length($NF))); print}')
          sed -e 's!\("version": \)"\(.*\)"!\1"'$(echo $BUMPED)'"!' -i manifest.json

      - uses: EndBug/add-and-commit@v9
        with:
          push: true
          add: 'manifest.json'
